# Introduction to Numpy

Python lists:

* are very flexible
* don't require uniform numerical types
* are very easy to modify (inserting or appending objects).

However, flexibility often comes at the cost of performance, and lists are not the ideal object for numerical calculations.

This is where **Numpy** comes in. Numpy is a Python module that defines a powerful n-dimensional array object that uses C and Fortran code behind the scenes to provide high performance.

In [2]:
import time
import math

a = range(10000000)

def func(a):
    return 1e-6*(4*a**2.) #7+1./(a+3)**3.4-(23*a)**4.2)-20

# measure how long it takes in seconds
start_time = time.time()

new_a = []
for val in a:
    new_a.append(func(val))
    
print(f'{time.time()-start_time} seconds')

2.666914939880371 seconds


In [3]:
import numpy

start_time = time.time()
a = numpy.array(a)
new_a = func(a)
print(f'{time.time()-start_time} seconds')

1.3238861560821533 seconds


The downside of Numpy arrays is that they have a more rigid structure, and require a single numerical type (e.g. floating point values), but for a lot of scientific work, this is exactly what is needed.

The Numpy module is imported with:

In [4]:
import numpy

Although in the rest of this course, and in many packages, the following convention is used:

In [5]:
import numpy as np

This is because Numpy is so often used that it is shorter to type ``np`` than ``numpy``.

## Creating Numpy arrays

The easiest way to create an array is from a Python list, using the ``array`` function:

In [6]:
a = np.array([10, 20, 30, 40])

In [7]:
a

array([10, 20, 30, 40])

In [8]:
L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2

255 µs ± 14.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
964 ns ± 12.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Numpy arrays have several attributes that give useful information about the array:

In [9]:
a.ndim  # number of dimensions

1

In [10]:
a.shape  # shape of the array

(1000,)

In [11]:
a.dtype  # numerical type

dtype('int64')

There are several other ways to create arrays. For example, there is an ``arange`` function that can be used similarly to the built-in Python ``range`` function, with the exception that it can take floating-point input:

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3, 12, 2)

array([ 3,  5,  7,  9, 11])

In [14]:
np.arange(1.2, 4.4, 0.1)

array([1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4,
       2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
       3.8, 3.9, 4. , 4.1, 4.2, 4.3])

Another useful function is ``linspace``, which can be used to create linearly spaced values between and including limits:

In [15]:
np.linspace(11., 12., 11)

array([11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ])

and a similar function can be used to create logarithmically spaced values between and including limits:

In [16]:
np.logspace(1., 4., 7)

array([   10.        ,    31.6227766 ,   100.        ,   316.22776602,
        1000.        ,  3162.27766017, 10000.        ])

Finally, the ``zeros`` and ``ones`` functions can be used to create arrays intially set to ``0`` and ``1`` respectively:

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

## Exercise

Create an array which contains 11 values logarithmically spaced between $10^{-20}$ and $10^{-10}$.

In [19]:
# your solution here

Create an array which contains the value 2 repeated 10 times

In [20]:
# your solution here

Try using ``np.empty(10)`` and compare the results to ``np.zeros(10)`` - why do you think there is a difference?

In [21]:
# your solution here

Create an array containing 5 times the value 0, as a 32-bit floating point array (this is harder)

In [22]:
# your solution here

## Combining arrays

Numpy arrays can be combined numerically using the standard ``+-*/**`` operators:

In [86]:
x1 = np.array([1,2,3])
y1 = np.array([4,5,6])

In [87]:
2 * y1

array([ 8, 10, 12])

In [75]:
import numpy as np

In [77]:
x + 2 * y

array([ 9, 12, 15])

In [78]:
x ** y

array([  1,  32, 729])

Note that this differs from lists:

In [79]:
x = [1,2,3]
y = [4,5,6]

In [83]:
y.append('hola')
y

[4, 5, 6, 'hola', 'hola']

In [85]:
3 * y

[4, 5, 6, 'hola', 'hola', 4, 5, 6, 'hola', 'hola', 4, 5, 6, 'hola', 'hola']

In [27]:
x + 2 * y

[1, 2, 3, 4, 5, 6, 4, 5, 6]

## Accessing and Slicing Arrays

Similarly to lists, items in arrays can be accessed individually:

In [88]:
x = np.array([9,8,7])

In [89]:
x[0]

9

In [90]:
x[1]

8

and arrays can also be **sliced** by specifiying the start and end of the slice (where the last element is exclusive):

In [92]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
y[0:5] # [start:end:step]

array([0, 1, 2, 3, 4])

optionally specifying a step:

In [94]:
y[0:10:2]

array([0, 2, 4, 6, 8])

As for lists, the start, end, and step are all optional, and default to ``0``, ``len(array)``, and ``1`` respectively:

In [34]:
y[:5]

array([0, 1, 2, 3, 4])

In [35]:
y[::2]

array([0, 2, 4, 6, 8])

## Exercise

Given an array ``x`` with 10 elements, find the array ``dx`` containing 9 values where ``dx[i] = x[i+1] - x[i]``. Do this without loops!

In [95]:
x = np.arange(10)
print(x)
dx = x[1:]-x[:9]
print(dx)

[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1 1]


In [96]:
# your solution here
x = np.linspace(3, 7, 10)
print(x)

dx = x[1:] - x[:-1]
print(dx)

dx2 = np.diff(x)
print(dx2)


[3.         3.44444444 3.88888889 4.33333333 4.77777778 5.22222222
 5.66666667 6.11111111 6.55555556 7.        ]
[0.44444444 0.44444444 0.44444444 0.44444444 0.44444444 0.44444444
 0.44444444 0.44444444 0.44444444]
[0.44444444 0.44444444 0.44444444 0.44444444 0.44444444 0.44444444
 0.44444444 0.44444444 0.44444444]


## Multi-dimensional arrays

<center> <img src="img/numpy_indexing.png" width="1600"/> </center>

In [ ]:
a[3:5, :6:2]

Numpy can be used for multi-dimensional arrays:

In [97]:
x = np.array([[1.,2.],[3.,4.]])

In [ ]:
x.

In [98]:
x.ndim

2

In [99]:
x.shape

(2, 2)

In [100]:
y = np.ones([3,2,3])  # ones takes the shape of the array, not the values

In [101]:
y

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [102]:
y.shape

(3, 2, 3)

Multi-dimensional arrays can be sliced differently along different dimensions:

In [43]:
z = np.ones([6,6,6])

In [44]:
z[::3, 1:4, :]

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

## Functions

In addition to an array class, Numpy contains a number of **vectorized** functions, which means functions that can act on all the elements of an array, typically much faster than could be achieved by looping over the array.

For example:

In [45]:
theta = np.linspace(0., 2. * np.pi, 10)

In [46]:
theta

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [47]:
np.sin(theta)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

Another useful package is the ``np.random`` sub-package, which can be used to genenerate random numbers fast:

In [48]:
# uniform distribution between 0 and 1
np.random.random(10)

array([0.34211037, 0.30741446, 0.60469684, 0.59454743, 0.69528636,
       0.63864015, 0.85032528, 0.89541654, 0.93350753, 0.5742706 ])

In [49]:
# 10 values from a gaussian distribution with mean 3 and sigma 1
np.random.normal(3., 1., 10)

array([2.60787935, 3.35823778, 4.33091641, 3.1976106 , 2.39446624,
       2.9635    , 3.22539271, 1.11169149, 4.34269815, 3.66495247])

Another very useful function in Numpy is [numpy.loadtxt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) which makes it easy to read in data from column-based data. For example, given the following file:

In [104]:
data = np.loadtxt('data/columns.txt')
data.ndim

2

Or we can read the individual columns:

In [106]:
_, temperature = np.loadtxt('data/columns.txt', unpack=True)

array([1995.00274, 1995.00548, 1995.00821, 1995.01095, 1995.01369,
       1995.01643, 1995.01916, 1995.0219 , 1995.02464, 1995.02738,
       1995.03012, 1995.03285, 1995.03559])

In [53]:
temperature

array([  0.944444,  -1.61111 ,  -3.55556 ,  -9.83333 , -10.2222  ,
        -9.5     , -10.2222  ,  -6.61111 ,  -2.94444 ,   1.55556 ,
         0.277778,  -1.44444 ,  -3.61111 ])

There are additional options to skip header rows, ignore comments, and read only certain columns. See the documentation for more details.

## Masking

The index notation ``[...]`` is not limited to single element indexing, or multiple element slicing, but one can also pass a discrete list/array of indices:

In [109]:
x = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])
x[[1,2,4,3,3,2]]

array([6, 4, 9, 7, 7, 4])

which is returning a new array composed of elements 1, 2, 4, etc from the original array.

Alternatively, one can also pass a boolean array of ``True/False`` values, called a **mask**, indicating which items to keep:

In [110]:
x[np.array([True, False, False, True, True, True, False, False, True, True, True, False, False, True])]

array([1, 7, 9, 3, 6, 7, 3, 3])

Now this doesn't look very useful because it is very verbose, but now consider that carrying out a comparison with the array will return such a boolean array:

In [111]:
x > 3.4

array([False,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True,  True, False])

It is therefore possible to extract subsets from an array using the following simple notation:

In [112]:
x[x > 3.4]

array([6, 4, 7, 9, 5, 6, 7, 4, 4])

Conditions can be combined:

In [113]:
x[(x > 3.4) & (x < 5.5)]

array([4, 5, 4, 4])

Of course, the boolean **mask** can be derived from a different array to ``x`` as long as it is the right size:

In [125]:
x = np.linspace(-1., 1., 14)
y = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])

In [117]:
y2 = y + 3
y2

array([ 4,  9,  7, 10, 12,  6,  4,  8,  9, 10,  6,  7,  7,  6])

In [119]:
yy = y[y2 >= 9]
yy

array([6, 7, 9, 6, 7])

In [121]:
y[(x > -0.5) | (x < 0.4)]

array([1, 6, 4, 7, 9, 3, 1, 5, 6, 7, 3, 4, 4, 3])

Since the mask itself is an array, it can be stored in a variable and used as a mask for different arrays:

In [61]:
keep = (x > -0.5) & (x < 0.4)
x_new = x[keep]
y_new = y[keep]

In [62]:
x_new

array([-0.38461538, -0.23076923, -0.07692308,  0.07692308,  0.23076923,
        0.38461538])

In [63]:
y_new

array([9, 3, 1, 5, 6, 7])

A mask can also appear on the left hand side of an assignment:

In [122]:
y

array([1, 6, 4, 7, 9, 3, 1, 5, 6, 7, 3, 4, 4, 3])

In [132]:
y[y > 5] = 3

In [133]:
y

array([1, 2, 4, 2, 2, 3, 1, 5, 2, 2, 3, 4, 4, 3])

### NaN values

In arrays, some of the values are sometimes NaN - meaning *Not a Number*. If you multiply a NaN value by another value, you get NaN, and if there are any NaN values in a summation, the total result will be NaN. One way to get around this is to use ``np.nansum`` instead of ``np.sum`` in order to find the sum:

In [134]:
x = np.array([1,2,3,np.nan])

In [135]:
np.sum(x)

nan

In [67]:
np.nansum(x)

6.0

In [68]:
np.nanmax(x)

3.0

You can also use ``np.isnan`` to tell you where values are NaN. For example, ``array[~np.isnan(array)]`` will return all the values that are not NaN (because ~ means 'not'):

In [69]:
np.isnan(x)

array([False, False, False,  True])

In [70]:
x[np.isnan(x)]

array([nan])

In [71]:
x[~np.isnan(x)]

array([1., 2., 3.])

### Statistics -- Scipy

In [72]:
import numpy.random as rnd


g = rnd.normal(loc=0, scale=1, size=1000000)

print(numpy.mean(g), numpy.median(g), numpy.std(g))

# specifying axis of operation gives different results:
a = [[1,1,1], [2,2,2], [3,3,3]]
print(numpy.mean(a))         # mean of all numbers in the array
print(numpy.mean(a, axis=0)) # mean along axis 0 (first axis = outermost axis = along columns)
print(numpy.mean(a, axis=1)) # mean along axis 1 (second axis = along rows)

# operations that ignore nans
b = [1, 2, 3, numpy.nan, 4, 5]
print(numpy.mean(b))    # returns nan
print(numpy.nanmean(b)) # ignores nan; see nanmedian, nanstd, ...

# determine percentiles
print(numpy.percentile(g, 50)) # the same as median
print(numpy.percentile(g, 68.27)-numpy.percentile(g, 31.73))

# create a histogram
hist, bins = numpy.histogram(g, bins=numpy.arange(-5, 6, 1))
print(bins)
print(hist)

0.00039163153195349973 0.00022096514599091084 1.0006909130302093
2.0
[2. 2. 2.]
[1. 2. 3.]
nan
3.0
0.00022096514599091084
0.9517683106088028
[-5 -4 -3 -2 -1  0  1  2  3  4  5]
[    36   1340  21503 135562 341470 341266 136027  21440   1321     35]


### Linear Algebra

In [73]:
import numpy.linalg as la

a = [1,2,3] 
b = [4,5,6]

print(numpy.dot(a,b)) # dot product
print(numpy.inner(a,b)) 
print(numpy.outer(a,b)) 

i = numpy.diag([1,2,3])
print(la.eig(i)) # return eigenvalues and eigenvectors
print(la.det(i)) # return determinant

# solve linear equations
a = [[3,2,-1], [2,-2,4], [-1,0.5,-1]]
b = [1,-2,0]
print(la.solve(a,b)) 

32
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
(array([1., 2., 3.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
6.0
[ 1. -2. -2.]


## Exercise

The [data/SIMAR_gaps.txt](data/SIMAR_gaps.txt) data file gives the wave climate data in the Mediterranean Sea.

Read in the file using ``np.loadtxt``. The data contains bad values, which you can identify by looking at the minimum and maximum values of the array. Use masking to get rid of the bad temperature values.

In [148]:
data = np.loadtxt('data/SIMAR_gaps.txt', skiprows=1)
data

array([[ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  3.700e+00,
         1.920e+02],
       [ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  5.000e+00,
         2.040e+02],
       [ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  5.700e+00,
         2.180e+02],
       ...,
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.910e+02,  4.900e+00,
         3.320e+02],
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.920e+02,  4.600e+00,
         3.550e+02],
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.930e+02,  5.700e+00,
         8.000e+00]])

In [150]:
H = data[:, 4]
print(np.min(H))
print(np.max(H))

-99.9
3.5


In [149]:
data_fil = data[H>-99.9, :]
H_fil = H[H>-99.9]

In [143]:
data.shape

(594, 18)

In [146]:
data_fil.shape
H_fil = data_fil[:, 4]
np.min(H_fil)

0.5

In [74]:

# your solution here
data = np.loadtxt('data/SIMAR_gaps.txt', skiprows=1)
print(data)
Hm0 = data[:, 4]
print(Hm0.min())

data[Hm0>-99.9, :]

[[ 2.016e+03  1.000e+00  1.000e+00 ... -9.990e+01  3.700e+00  1.920e+02]
 [ 2.016e+03  1.000e+00  1.000e+00 ... -9.990e+01  5.000e+00  2.040e+02]
 [ 2.016e+03  1.000e+00  1.000e+00 ... -9.990e+01  5.700e+00  2.180e+02]
 ...
 [ 2.016e+03  1.000e+00  3.100e+01 ...  2.910e+02  4.900e+00  3.320e+02]
 [ 2.016e+03  1.000e+00  3.100e+01 ...  2.920e+02  4.600e+00  3.550e+02]
 [ 2.016e+03  1.000e+00  3.100e+01 ...  2.930e+02  5.700e+00  8.000e+00]]
-99.9


array([[ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  3.700e+00,
         1.920e+02],
       [ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  5.000e+00,
         2.040e+02],
       [ 2.016e+03,  1.000e+00,  1.000e+00, ..., -9.990e+01,  5.700e+00,
         2.180e+02],
       ...,
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.910e+02,  4.900e+00,
         3.320e+02],
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.920e+02,  4.600e+00,
         3.550e+02],
       [ 2.016e+03,  1.000e+00,  3.100e+01, ...,  2.930e+02,  5.700e+00,
         8.000e+00]])