# Introduction to Numpy

Python lists:

* are very flexible
* don't require uniform numerical types
* are very easy to modify (inserting or appending objects).

However, flexibility often comes at the cost of performance, and lists are not the ideal object for numerical calculations.

This is where **Numpy** comes in. Numpy is a Python module that defines a powerful n-dimensional array object that uses C and Fortran code behind the scenes to provide high performance.

In [ ]:
import time
import math

a = range(10000000)

def func(a):
    return 1e-6*(4*a**2.) #7+1./(a+3)**3.4-(23*a)**4.2)-20

# measure how long it takes in seconds
start_time = time.time()

new_a = []
for val in a:
    new_a.append(func(val))
    
print(f'{time.time()-start_time} seconds')

In [ ]:
import numpy

start_time = time.time()
a = numpy.array(a)
new_a = func(a)
print(f'{time.time()-start_time} seconds')

In [ ]:
L = range(1000)
%timeit [i**2 for i in L]

a = np.arange(1000)
%timeit a**2

The downside of Numpy arrays is that they have a more rigid structure, and require a single numerical type (e.g. floating point values), but for a lot of scientific work, this is exactly what is needed.

The Numpy module is imported with:

In [ ]:
import numpy

Although in the rest of this course, and in many packages, the following convention is used:

In [1]:
import numpy as np

This is because Numpy is so often used that it is shorter to type ``np`` than ``numpy``.

## Creating Numpy arrays

The easiest way to create an array is from a Python list, using the ``array`` function:

In [11]:
a = np.array([10, 20.1, 30, 40])

In [14]:
b = list()
for n in range(5):
    b.append(n)
c = np.array(b)
c

array([0, 1, 2, 3, 4])

In [3]:
type(a)

numpy.ndarray

Numpy arrays have several attributes that give useful information about the array:

In [4]:
a.ndim  # number of dimensions

1

In [5]:
a.shape  # shape of the array

(4,)

In [10]:
a.dtype  # numerical type

dtype('float64')

There are several other ways to create arrays. For example, there is an ``arange`` function that can be used similarly to the built-in Python ``range`` function, with the exception that it can take floating-point input:

In [24]:
d =np.arange(1, 5, 1)
# np.arange(0, 10, 1)

In [25]:
d.dtype

dtype('int64')

In [ ]:
np.arange(30.5)

In [ ]:
np.arange(3, 12, 2)

In [26]:
b = np.arange(1.2, 4.41, 0.1)


In [28]:
b

array([1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4,
       2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
       3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4])

In [30]:
b[3]

1.5000000000000002

Another useful function is ``linspace``, which can be used to create linearly spaced values between and including limits:

In [ ]:
np.linspace(11, 12, 10)

and a similar function can be used to create logarithmically spaced values between and including limits:

In [12]:
np.logspace(1., 4., 7)

array([   10.        ,    31.6227766 ,   100.        ,   316.22776602,
        1000.        ,  3162.27766017, 10000.        ])

Finally, the ``zeros`` and ``ones`` functions can be used to create arrays intially set to ``0`` and ``1`` respectively:

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

np.array([X, X, X, X])

np.arange(start, finish, step)

np.linspace(start, finish-included, number of elements)

np.zeros([dim, dim]) 1D: np.zeros(X)

np.ones([dim, dim])

np.empty([dim, dim])

In [36]:
a 

array([10. , 20.1, 30. , 40. ])

In [37]:
b

array([1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4,
       2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
       3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4])

In [39]:
c = np.stack([a, a])
c

array([[10. , 20.1, 30. , 40. ],
       [10. , 20.1, 30. , 40. ]])

In [40]:
np.shape(c)

(2, 4)

In [42]:
d = np.vstack([a, a])
d

array([[10. , 20.1, 30. , 40. ],
       [10. , 20.1, 30. , 40. ]])

In [45]:
e = np.hstack([a, b])

In [46]:
np.shape(e)

(37,)

## Exercise

Create an array which contains the value 2 repeated 10 times

Create an array which contains values from 1 until 90 every one and then the values 95, 99, 99.9, 99.99.

## Numerical operations with arrays

Numpy arrays can be combined numerically using the standard ``+-*/**`` operators:

In [54]:
x1 = np.array([1,2,3])
y1 = np.array([4,5,6])

In [59]:
y1

array([4, 5, 6])

In [60]:
2 * y1

array([ 8, 10, 12])

In [62]:
(x1 + 2) * y1

array([12, 20, 30])

In [65]:
x1 ** y1

array([  1,  32, 729])

Note that this differs from lists:

In [66]:
x = [1,2,3]
y = [4,5,6]

In [67]:
y.append('hola')
y

[4, 5, 6, 'hola']

In [70]:
3 * y

[4, 5, 6, 'hola', 4, 5, 6, 'hola', 4, 5, 6, 'hola']

In [72]:
2 * y

[4, 5, 6, 'hola', 4, 5, 6, 'hola']

In [69]:
x + 2 * y

[1, 2, 3, 4, 5, 6, 'hola', 4, 5, 6, 'hola']

## Accessing and Slicing Arrays

Similarly to lists, items in arrays can be accessed individually:

In [73]:
x = np.array([9,8,7])

In [74]:
x

array([9, 8, 7])

In [75]:
x[0]

9

In [76]:
x[1]

8

and arrays can also be **sliced** by specifiying the start and end of the slice (where the last element is exclusive):

In [77]:
y = np.arange(10, 20)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [79]:
y[0:5:2] # Slices [start:end:step]

array([10, 12, 14])

optionally specifying a step:

In [ ]:
y[0:10:2]

As for lists, the start, end, and step are all optional, and default to ``0``, ``len(array)``, and ``1`` respectively:

In [80]:
y[:5]

array([10, 11, 12, 13, 14])

In [81]:
y[::2]

array([10, 12, 14, 16, 18])

## Exercise

Given an array ``x`` with 20 elements, find the array ``dx`` containing 19 values where ``dx[i] = x[i+1] - x[i]``. Do this without loops!

## Multi-dimensional arrays

<center> <img src="img/numpy_indexing.png" width="1600"/> </center>

In [104]:
y = np.ones([3,2,3])  # ones takes the shape of the array, not the values

In [108]:
y.shape

(3, 2, 3)

In [109]:
y

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

Multi-dimensional arrays can be sliced differently along different dimensions:

In [106]:
z = np.ones([6,6,6])

In [107]:
z[::3, 1:4, :]

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

## Constants

NumPy provides us access to some useful constants as well - remember you should never be typing these in manually! Other libraries such as SciPy and MetPy have their own set of constants that are more domain specific.

In [110]:
np.pi

3.141592653589793

In [111]:
np.e

2.718281828459045

In [112]:
1 + np.pi

4.141592653589793

## Functions

In addition to an array class, Numpy contains a number of **vectorized** functions, which means functions that can act on all the elements of an array, typically much faster than could be achieved by looping over the array.

For example:

In [113]:
theta = np.linspace(0., 2. * np.pi, 10)

In [114]:
theta.shape

(10,)

In [116]:
np.shape(theta)

(10,)

In [118]:
theta.max()

6.283185307179586

In [119]:
np.max(theta)

6.283185307179586

In [ ]:
aa = np.array([np.linspace(0., 2. * np.pi, 10), np.linspace(0., 2. * np.pi, 10)])

In [ ]:
pp = [np.linspace(0., 2. * np.pi, 10), np.linspace(0., 2. * np.pi, 10)]
pp

In [ ]:
type(pp)

In [ ]:
aa = np.asarray(pp)

In [ ]:
aa.shape

In [ ]:
np.sin(aa)

In [ ]:
np.sin(aa[0, 0])

Another useful package is the ``np.random`` sub-package, which can be used to genenerate random numbers fast:

In [120]:
# uniform distribution between 0 and 1
np.random.random(10)

array([0.48849716, 0.52766269, 0.83970123, 0.85602101, 0.64405742,
       0.54420396, 0.65176724, 0.44591857, 0.1544168 , 0.2488368 ])

In [121]:
# 10 values from a gaussian distribution with mean 3 and sigma 1
np.random.normal(3., 1., 10)

array([2.61840403, 2.16555013, 4.04433245, 5.64950756, 3.73826699,
       2.84408076, 2.61227934, 2.99571071, 2.28552334, 3.71846935])

In [123]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [ ]:
a.shape

In [ ]:
np.sum(a, axis=1)

Another very useful function in Numpy is [numpy.loadtxt](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) which makes it easy to read in data from column-based data. For example, given the following file:

In [131]:
from pathlib import Path

dir_data = Path('data')
data = np.loadtxt(dir_data / 'columns.txt')

In [132]:
data

array([[ 1.99500274e+03,  9.44444000e-01],
       [ 1.99500548e+03, -1.61111000e+00],
       [ 1.99500821e+03, -3.55556000e+00],
       [ 1.99501095e+03, -9.83333000e+00],
       [ 1.99501369e+03, -1.02222000e+01],
       [ 1.99501643e+03, -9.50000000e+00],
       [ 1.99501916e+03, -1.02222000e+01],
       [ 1.99502190e+03, -6.61111000e+00],
       [ 1.99502464e+03, -2.94444000e+00],
       [ 1.99502738e+03,  1.55556000e+00],
       [ 1.99503012e+03,  2.77778000e-01],
       [ 1.99503285e+03, -1.44444000e+00],
       [ 1.99503559e+03, -3.61111000e+00]])

## Masking

The index notation ``[...]`` is not limited to single element indexing, or multiple element slicing, but one can also pass a discrete list/array of indices:

In [145]:
x = np.array([1,6,4,7, 9, 8, 10])
#x[[True, False, True, False]]

which is returning a new array composed of elements 1, 2, 4, etc from the original array.

Alternatively, one can also pass a boolean array of ``True/False`` values, called a **mask**, indicating which items to keep:

In [136]:
y = np.array([3, 4, 5])

In [137]:
mask = np.array([True, False, False])

In [138]:
y[mask]

array([3])

Now this doesn't look very useful because it is very verbose, but now consider that carrying out a comparison with the array will return such a boolean array:

In [141]:
x

array([ 1,  6,  4,  7,  9,  8, 10])

In [146]:
mask = x > 3.4

It is therefore possible to extract subsets from an array using the following simple notation:

In [149]:
x[x > 3.4]

array([ 6,  4,  7,  9,  8, 10])

In [150]:
x[mask]

array([ 6,  4,  7,  9,  8, 10])

In [151]:
x[~mask]

array([1])

Conditions can be combined:

### Conditional formating

##### Loops
and, or

#### Masking in numpy array
& (and), | (or)

In [152]:
x

array([ 1,  6,  4,  7,  9,  8, 10])

In [153]:
x[(x > 3.4) & (x < 5.5)]

array([4])

Of course, the boolean **mask** can be derived from a different array to ``x`` as long as it is the right size:

In [154]:
x = np.linspace(-1., 1., 14)
y = np.array([1,6,4,7,9,3,1,5,6,7,3,4,4,3])

In [155]:
y.shape

(14,)

In [156]:
x.shape

(14,)

In [157]:
y2 = y + 3
y2

array([ 4,  9,  7, 10, 12,  6,  4,  8,  9, 10,  6,  7,  7,  6])

In [158]:
mask = y2 >= 9
yy = y[mask]
yy

array([6, 7, 9, 6, 7])

In [160]:
y[(x > -0.5) | (x < 0.4)]

array([1, 6, 4, 7, 9, 3, 1, 5, 6, 7, 3, 4, 4, 3])

Since the mask itself is an array, it can be stored in a variable and used as a mask for different arrays:

In [159]:
keep = (x > -0.5) & (x < 0.4)
x_new = x[keep]
y_new = y[keep]

In [ ]:
keep

In [ ]:
x_new

In [ ]:
y_new

we can use this conditional indexing to assign new values to certain positions within our array, somewhat like a masking operation.

In [161]:
y

array([1, 6, 4, 7, 9, 3, 1, 5, 6, 7, 3, 4, 4, 3])

In [163]:
mask = y>5
mask

array([False,  True, False,  True,  True, False, False, False,  True,
        True, False, False, False, False])

In [165]:
y[mask] = 999

In [166]:
y

array([  1, 999,   4, 999, 999,   3,   1,   5, 999, 999,   3,   4,   4,
         3])

In [ ]:
y1 = y[mask]
y1

In [ ]:
mm = y > 3

In [ ]:
y[mm] = np.nan

In [ ]:
y[y > 5] = 3

### NaN values

In arrays, some of the values are sometimes NaN - meaning *Not a Number*. If you multiply a NaN value by another value, you get NaN, and if there are any NaN values in a summation, the total result will be NaN. One way to get around this is to use ``np.nansum`` instead of ``np.sum`` in order to find the sum:

In [172]:
x = np.array([1,2,3,np.NaN])
x

array([ 1.,  2.,  3., nan])

In [171]:
np.NAN # np.nan | np.NaN | np.NAN

nan

In [174]:
np.nansum(x)

6.0

In [ ]:
np.nansum(x)

In [175]:
np.nanmax(x)

3.0

You can also use ``np.isnan`` to tell you where values are NaN. For example, ``array[~np.isnan(array)]`` will return all the values that are not NaN (because ~ means 'not'):

In [176]:
np.isnan(x)

array([False, False, False,  True])

In [177]:
x[np.isnan(x)]

array([nan])

In [178]:
x[~np.isnan(x)]

array([1., 2., 3.])

### Statistics --> Scipy

In [ ]:
import numpy.random as rnd


g = rnd.normal(loc=0, scale=1, size=1000000)

print(numpy.mean(g), numpy.median(g), numpy.std(g))

# specifying axis of operation gives different results:
a = [[1,1,1], [2,2,2], [3,3,3]]
print(numpy.mean(a))         # mean of all numbers in the array
print(numpy.mean(a, axis=0)) # mean along axis 0 (first axis = outermost axis = along columns)
print(numpy.mean(a, axis=1)) # mean along axis 1 (second axis = along rows)

# operations that ignore nans
b = [1, 2, 3, numpy.nan, 4, 5]
print(numpy.mean(b))    # returns nan
print(numpy.nanmean(b)) # ignores nan; see nanmedian, nanstd, ...

# determine percentiles
print(numpy.percentile(g, 50)) # the same as median
print(numpy.percentile(g, 68.27)-numpy.percentile(g, 31.73))

# create a histogram
hist, bins = numpy.histogram(g, bins=numpy.arange(-5, 6, 1))
print(bins)
print(hist)

## Exercise

The [data/SIMAR_gaps.txt](data/SIMAR_gaps.txt) data file gives the wave climate data in the Mediterranean Sea.

Read in the file using ``np.loadtxt``. The data contains bad values, which you can identify by looking at the minimum and maximum values of the array. Use masking to get rid of the bad values.

In [1]:
from pathlib import Path
dir_data = Path('data')
data = np.loadtxt(dir_data / 'SIMAR_gaps.txt', skiprows=1)
#np.genfromtxt()
var = data[:, 4]

NameError: name 'np' is not defined

### Linear Algebra

In [180]:
import numpy
import numpy.linalg as la

a = [1,2,3] 
b = [4,5,6]

print(numpy.dot(a,b)) # dot product
print(numpy.inner(a,b)) 
print(numpy.outer(a,b)) 

i = numpy.diag([1,2,3])
print(la.eig(i)) # return eigenvalues and eigenvectors
print(la.det(i)) # return determinant

# solve linear equations
a = [[3,2,-1], [2,-2,4], [-1,0.5,-1]]
b = [1,-2,0]
print(la.solve(a,b)) 

32
32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
(array([1., 2., 3.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
6.0
[ 1. -2. -2.]
